ln -s $DOTFILES/ssh ~/.ssh
ln -s $DOTFILES/public/zshrc ~/.zshrc
ln -s $DOTFILES/config/vimrc ~/.vimrc
ln -s $DOTFILES/config/gitconfig ~/.gitconfig
ln -s $DOTFILES/public/gitignore_global ~/.gitignore_global
ln -s $DOTFILES/pythonrc ~/.pythonrc
ln -s $DOTFILES/history/$HOSTNAME/ptpython_history ~/.ptpython/history
ln -s $DOTFILES/config/ptpython/config.py ~/.ptpython/config.py
ln -s $DOTFILES/public/tmux.conf ~/.tmux.conf
ln -s $DOTFILES/config/$HOSTNAME/tmux.conf ~/tmux_extra
ln -s $DOTFILES/jupyter ~/.jupyter
