ln -s $DOTFILES/ssh ~/.ssh
ln -s $DOTFILES/zsh ~/.zsh
ln -s $DOTFILES/public/zshrc ~/.zshrc
ln -s $DOTFILES/zsh_history ~/.zsh_history
ln -s $DOTFILES/vimrc ~/.vimrc
ln -s $DOTFILES/gitconfig ~/.gitconfig
ln -s $DOTFILES/pythonrc ~/.pythonrc
ln -s $DOTFILES/vimrc ~/.vimrc
ln -s $DOTFILES/public/ptpython ~/.ptpython
