ln -s ~/dotfiles/ssh ~/.ssh
ln -s ~/dotfiles/zsh ~/.zsh
ln -s ~/dotfiles/public/zshrc ~/.zshrc
ln -s ~/dotfiles/zsh_history ~/.zsh_history
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/pythonrc ~/.pythonrc
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/public/ptpython ~/.ptpython
